# Generated by Django 5.1.6 on 2025-02-11 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grzesznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiadz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MetodaPlatnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UslugaDodatkowa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ZamowienieOdpustu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_odpustu', models.CharField(choices=[('cal', 'Odpust Całkowity'), ('czes', 'Odpust Częściowy')], max_length=4)),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_zamowienia', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('wykonane', models.BooleanField(default=False)),
                ('grzesznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odpusty.grzesznik')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odpusty.klient')),
                ('ksiadz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odpusty.ksiadz')),
                ('metoda_platnosci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odpusty.metodaplatnosci')),
                ('uslugi_dodatkowe', models.ManyToManyField(blank=True, to='odpusty.uslugadodatkowa')),
            ],
        ),
    ]
